### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by josefnorlin**
Updated with likspie208's solution with another variable, but without any css and other changes.
The solution where he removed the variable didn't work for me, hence this solution.

I say this would be the best solution so far since we're many who anticipates a working ngx-croppie library for Angular. If we find a solution in the future that can remove the extra added variable we can change that later.

### CODE REVIEW

**Comment by deej81** [comment]
would rather avoid that extra variable if I can; can you check if this branch does what you need?

https://github.com/deej81/ngx-croppie/tree/multi-image-fix

**Comment by deej81** [comment]
version 2.0.0 contains the fix, so I'll close this pull request. Thanks for submitting code, its appreciated.

**Comment by josefnorlin** [comment]
Thank you for a great library! And great work! :)

Den fre 18 jan. 2019 kl 11:09 skrev Dan Jordan <notifications@github.com>:

**Comment by likspie208** [comment]
Ah, missed some action ! I was having some health issues and got admitted to the hospital. Good to see some activity and the issue finally resolved.
@josefnorlin That was my very first pull request, and as you guys rightly pointed out, I had edited the code-base in a non-standard way ( which suited my project need: needed a circular image and stuff ).

But it **works** for me with the variable _removed_ - click the "demo" link in [this](https://github.com/likspie208/ngx-croppie) page or just clone and "ng-serve".
Anyway, good to see it finally figured out. :+1:  Thanks to yours and @deej81 's efforts.

**Comment by likspie208** [comment]
@deej81 :+1: on the new version. You know, I didn't really mean to make so much of those changes: the README file and CSS. Sorry about that.
Besides, I thought you could always omit changes that was unnecessary. I left it for you to sort out. I thought - maybe if you liked "keep", otherwise "omit".
But never mind. It definitely helped with my work and sure it would serve a lot more developers. Happy to see the updated version with the fix in. Good luck :+1:

**Pull request closed without merging**
